"$schema" = 'https://starship.rs/config-schema.json'

format = """
[‚ñë‚ñí‚ñì‚ñà](lavender)\
$os\
[ÓÇ¥](bg:red fg:lavender)\
$username\
[ÓÇ∞](bg:peach fg:red)\
$directory\
[ÓÇ∞](bg:yellow fg:peach)\
$git_branch\
$git_status\
[ÓÇ∞](bg:teal fg:yellow)\
$time\
[ÓÇ¥](fg:teal)\
$container\
$cmd_duration\
$line_break\
\n\
$character"""

right_format = """
$nodejs\
$bun\
$deno\
$python\
$rust\
$golang\
$java\
$kotlin\
$scala\
$c\
$cpp\
$dotnet\
$ruby\
$php\
$lua\
$perl\
$elixir\
$erlang\
$haskell\
$ocaml\
$nim\
$zig\
$swift\
$dart\
$julia\
$rlang\
$vlang\
$gleam\
$crystal\
$solidity\
$elm\
$purescript\
$raku\
$red\
$fennel\
$odin\
$mojo\
"""

palette = 'catppuccin_latte'

[os]
disabled = false
style = "bg:lavender fg:crust"

[os.symbols]
Windows = "Óúè "
Ubuntu = "Û∞ïà "
SUSE = "Ôåî "
Raspbian = "Û∞êø "
Mint = "Û∞£≠ "
Macos = "Û∞Äµ "
Manjaro = "Ôåí "
Linux = "Û∞åΩ "
Gentoo = "Û∞£® "
Fedora = "Û∞£õ "
Alpine = "ÔåÄ "
Amazon = "Ôâ∞ "
Android = "Óúé "
Arch = "Û∞£á "
Artix = "Û∞£á "
CentOS = "ÔåÑ "
Debian = "Û∞£ö "
Redhat = "Û±Ñõ "
RedHatEnterprise = "Û±Ñõ "
NixOS = "Ôåì "

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ [Ó¥µ](bg:red fg:blue) $user]($style)'

[directory]
style = "bg:peach fg:crust"
format = "[ [Û∞âã](fg:yellow bg:peach) $path]($style)"
truncation_length = 3
truncation_symbol = "‚Ä¶/"
home_symbol = '~'

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music" = "Û∞ùö "
"Pictures" = "ÔÄæ "
"Developer" = "Û∞≤ã "

[git_branch]
symbol = "Ôêò"
style = "bg:yellow"
format = '[[ $symbol $branch ](fg:crust bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:crust bg:yellow)]($style)'


[nodejs]
symbol = "Óúò"
style = "bg:lang_javascript fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_javascript)[ $symbol( $version) ](fg:crust bg:lang_javascript)[ÓÇ¥](fg:lang_javascript)]($style)'

[bun]
symbol = "ÓùØ"
style = "bg:lang_bun fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_bun)[ $symbol( $version) ](fg:crust bg:lang_bun)[ÓÇ¥](fg:lang_bun)]($style)'

[deno]
symbol = "ÓüÄ"
style = "bg:lang_deno fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_deno)[ $symbol( $version) ](fg:crust bg:lang_deno)[ÓÇ¥](fg:lang_deno)]($style)'

[python]
symbol = "Óúº"
style = "bg:lang_python fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_python)[ $symbol( $version)(\($virtualenv\)) ](fg:crust bg:lang_python)[ÓÇ¥](fg:lang_python)]($style)'

[rust]
symbol = "Óû®"
style = "bg:lang_rust fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_rust)[ $symbol( $version) ](fg:crust bg:lang_rust)[ÓÇ¥](fg:lang_rust)]($style)'

[golang]
symbol = "Óòß"
style = "bg:lang_go fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_go)[ $symbol( $version) ](fg:crust bg:lang_go)[ÓÇ¥](fg:lang_go)]($style)'

[java]
symbol = "Óú∏"
style = "bg:lang_java fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_java)[ $symbol( $version) ](fg:crust bg:lang_java)[ÓÇ¥](fg:lang_java)]($style)'

[kotlin]
symbol = "Ó†õ"
style = "bg:lang_kotlin fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_kotlin)[ $symbol( $version) ](fg:crust bg:lang_kotlin)[ÓÇ¥](fg:lang_kotlin)]($style)'

[scala]
symbol = "Óú∑"
style = "bg:lang_scala fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_scala)[ $symbol( $version) ](fg:crust bg:lang_scala)[ÓÇ¥](fg:lang_scala)]($style)'

[c]
symbol = "Óòû"
style = "bg:lang_c fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_c)[ $symbol( $version) ](fg:crust bg:lang_c)[ÓÇ¥](fg:lang_c)]($style)'

[cpp]
symbol = "ÓôÜ"
style = "bg:lang_cpp fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_cpp)[ $symbol( $version) ](fg:crust bg:lang_cpp)[ÓÇ¥](fg:lang_cpp)]($style)'

[dotnet]
symbol = "ÓüÜ"
style = "bg:lang_dotnet fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_dotnet)[ $symbol( $version) ](fg:crust bg:lang_dotnet)[ÓÇ¥](fg:lang_dotnet)]($style)'

[ruby]
symbol = "Óúπ"
style = "bg:lang_ruby fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_ruby)[ $symbol( $version) ](fg:crust bg:lang_ruby)[ÓÇ¥](fg:lang_ruby)]($style)'

[php]
symbol = "ÓúΩ"
style = "bg:lang_php fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_php)[ $symbol( $version) ](fg:crust bg:lang_php)[ÓÇ¥](fg:lang_php)]($style)'

[lua]
symbol = "Óò†"
style = "bg:lang_lua fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_lua)[ $symbol( $version) ](fg:crust bg:lang_lua)[ÓÇ¥](fg:lang_lua)]($style)'

[perl]
symbol = "Óôæ"
style = "bg:lang_perl fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_perl)[ $symbol( $version) ](fg:crust bg:lang_perl)[ÓÇ¥](fg:lang_perl)]($style)'

[elixir]
symbol = "Óò≠"
style = "bg:lang_elixir fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_elixir)[ $symbol( $version) ](fg:crust bg:lang_elixir)[ÓÇ¥](fg:lang_elixir)]($style)'

[erlang]
symbol = "Óû±"
style = "bg:lang_erlang fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_erlang)[ $symbol( $version) ](fg:crust bg:lang_erlang)[ÓÇ¥](fg:lang_erlang)]($style)'

[haskell]
symbol = "Óù∑"
style = "bg:lang_haskell fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_haskell)[ $symbol( $version) ](fg:crust bg:lang_haskell)[ÓÇ¥](fg:lang_haskell)]($style)'

[ocaml]
symbol = "Ó°é"
style = "bg:lang_ocaml fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_ocaml)[ $symbol( $version) ](fg:crust bg:lang_ocaml)[ÓÇ¥](fg:lang_ocaml)]($style)'

[nim]
symbol = "Ó°Å"
style = "bg:lang_nim fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_nim)[ $symbol( $version) ](fg:crust bg:lang_nim)[ÓÇ¥](fg:lang_nim)]($style)'

[zig]
symbol = "Ó£Ø"
style = "bg:lang_zig fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_zig)[ $symbol( $version) ](fg:crust bg:lang_zig)[ÓÇ¥](fg:lang_zig)]($style)'

[swift]
symbol = "Óùï"
style = "bg:lang_swift fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_swift)[ $symbol( $version) ](fg:crust bg:lang_swift)[ÓÇ¥](fg:lang_swift)]($style)'

[dart]
symbol = "Óôå"
style = "bg:lang_dart fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_dart)[ $symbol( $version) ](fg:crust bg:lang_dart)[ÓÇ¥](fg:lang_dart)]($style)'

[julia]
symbol = "Ó†ç"
style = "bg:lang_julia fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_julia)[ $symbol( $version) ](fg:crust bg:lang_julia)[ÓÇ¥](fg:lang_julia)]($style)'

[rlang]
symbol = "Û∞üî"
style = "bg:lang_rlang fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_rlang)[ $symbol( $version) ](fg:crust bg:lang_rlang)[ÓÇ¥](fg:lang_rlang)]($style)'

[vlang]
symbol = "Óö¨"
style = "bg:lang_vlang fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_vlang)[ $symbol( $version) ](fg:crust bg:lang_vlang)[ÓÇ¥](fg:lang_vlang)]($style)'

[gleam]
symbol = "Û∞¶•"
style = "bg:lang_gleam fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_gleam)[ $symbol( $version) ](fg:crust bg:lang_gleam)[ÓÇ¥](fg:lang_gleam)]($style)'

[crystal]
symbol = "Óû¨"
style = "bg:lang_crystal fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_crystal)[ $symbol( $version) ](fg:crust bg:lang_crystal)[ÓÇ¥](fg:lang_crystal)]($style)'

[solidity]
symbol = "Ó¢¶"
style = "bg:lang_solidity fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_solidity)[ $symbol( $version) ](fg:crust bg:lang_solidity)[ÓÇ¥](fg:lang_solidity)]($style)'

[elm]
symbol = "Óüé"
style = "bg:lang_elm fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_elm)[ $symbol( $version) ](fg:crust bg:lang_elm)[ÓÇ¥](fg:lang_elm)]($style)'

[purescript]
symbol = "Ó°µ"
style = "bg:lang_purescript fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_purescript)[ $symbol( $version) ](fg:crust bg:lang_purescript)[ÓÇ¥](fg:lang_purescript)]($style)'

[raku]
symbol = "Û±ñä"
style = "bg:lang_raku fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_raku)[ $symbol( $version) ](fg:crust bg:lang_raku)[ÓÇ¥](fg:lang_raku)]($style)'

[red]
symbol = "Û±•í"
style = "bg:lang_red fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_red)[ $symbol( $version) ](fg:crust bg:lang_red)[ÓÇ¥](fg:lang_red)]($style)'

[fennel]
symbol = "ÓöØ"
style = "bg:lang_fennel fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_fennel)[ $symbol( $version) ](fg:crust bg:lang_fennel)[ÓÇ¥](fg:lang_fennel)]($style)'

[odin]
symbol = "√ò"
style = "bg:lang_odin fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_odin)[ $symbol( $version) ](fg:crust bg:lang_odin)[ÓÇ¥](fg:lang_odin)]($style)'

[mojo]
symbol = "üî•"
style = "bg:lang_mojo fg:crust bold"
format = '[[ ÓÇ∂](fg:lang_mojo)[ $symbol( $version) ](fg:crust bg:lang_mojo)[ÓÇ¥](fg:lang_mojo)]($style)'

[docker_context]
symbol = "Ôåà"
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[conda]
symbol = "ÔÑå"
style = "fg:crust bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false


[time]
disabled = false
time_format = "%R"
style = "bg:teal"
format = '[[ Ôê∫ $time ](fg:crust bg:teal)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[Û∞òç](bold fg:green)'
error_symbol = '[ÔÄç](bold fg:red)'
vimcmd_symbol = '[Û∞∞ì](bold fg:teal)'
vimcmd_replace_one_symbol = '[Û∞∞ü](bold fg:lavender)'
vimcmd_replace_symbol = '[Û∞¨ô](bold fg:maroon)'
vimcmd_visual_symbol = '[Û∞∞´](bold fg:base)'

[cmd_duration]
show_milliseconds = true
format = "Ó´¥ in $duration "
style = "bg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000
min_time = 1000

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

lang_javascript = "#F7DF1E"
lang_bun = "#FBF0DF"
lang_deno = "#000000"
lang_python = "#3776AB"
lang_rust = "#DEA584"
lang_go = "#00ADD8"
lang_java = "#ED8B00"
lang_kotlin = "#7F52FF"
lang_scala = "#DC322F"
lang_c = "#A8B9CC"
lang_cpp = "#00599C"
lang_dotnet = "#512BD4"
lang_ruby = "#CC342D"
lang_php = "#777BB4"
lang_lua = "#2C2D72"
lang_perl = "#39457E"
lang_elixir = "#4B275F"
lang_erlang = "#A90533"
lang_haskell = "#5D4F85"
lang_ocaml = "#EC6813"
lang_nim = "#FFE953"
lang_zig = "#F7A41D"
lang_swift = "#F05138"
lang_dart = "#0175C2"
lang_julia = "#9558B2"
lang_rlang = "#276DC3"
lang_vlang = "#5D87BF"
lang_gleam = "#FFAFF3"
lang_crystal = "#000000"
lang_solidity = "#363636"
lang_elm = "#1293D8"
lang_purescript = "#14161A"
lang_raku = "#0298C3"
lang_red = "#E60000"
lang_fennel = "#FFF3D7"
lang_odin = "#3882D2"
lang_mojo = "#FF7000"
